# Машинное обучение, ФКН ВШЭ

# Практическое задание 1

## Общая информация

Срок сдачи: 28.10.2023 14:40

### О задании

Практическое задание 1 посвящено изучению основных библиотек для анализа данных, а также линейных моделей и методов их обучения. Вы научитесь:
 * применять библиотеки NumPy и Pandas для осуществления желаемых преобразований;
 * подготавливать данные для обучения линейных моделей;
 * обучать линейную, Lasso и Ridge-регрессии при помощи модуля scikit-learn;
 * реализовывать обычный и стохастический градиентные спуски;
 * обучать линейную регрессию для произвольного функционала качества.
 

### Оценивание и штрафы

Каждая из задач имеет определенную «стоимость» (указана в скобках около задачи). Максимально допустимая оценка за работу — 10 баллов. Кроме того, некоторые из заданий являются опциональными (необязательными), однако за их выполнение можно получить дополнительные баллы.

Сдавать задание после указанного срока сдачи нельзя. При выставлении неполного балла за задание в связи с наличием ошибок на усмотрение проверяющего предусмотрена возможность исправить работу на указанных в ответном письме условиях.

Задание выполняется самостоятельно. «Похожие» решения считаются плагиатом и все задействованные студенты (в том числе те, у кого списали) не могут получить за него больше 0 баллов. Если вы нашли решение какого-то из заданий (или его часть) в открытом источнике, необходимо указать ссылку на этот источник в отдельном блоке в конце Вашей работы (скорее всего вы будете не единственным, кто это нашел, поэтому чтобы исключить подозрение в плагиате, необходима ссылка на источник). 

Неэффективная реализация кода может негативно отразиться на оценке.


### Формат сдачи
Для сдачи задания переименуйте получившийся файл \*.ipynb в соответствии со следующим форматом: *HW1_Username.ipynb*, где *Username* — Ваша фамилия и инициалы на латинице (например, *HW1_IvanovII.ipynb*). Далее отправьте этот файл на bobrovskaya_op@surgu.ru или Smorodinov-1990@mail.ru.

## Библиотеки для анализа данных

### NumPy

Во всех заданиях данного раздела запрещено использовать циклы  и list comprehensions. Под вектором и матрицей в данных заданиях понимается одномерный и двумерный numpy.array соответственно.

In [1]:
import numpy as np

**1. (0.2 балла)** Реализуйте функцию, возвращающую максимальный элемент в векторе x среди элементов, перед которыми стоит нулевой. Для x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) ответом является 5. Если нулевых элементов нет, функция должна возвращать None.


In [8]:
def max_after_zero(x):
    zero_indices = np.where(x == 0)[0]
    
    if len(zero_indices) == 0:
        return None
    
    # Фильтруем индексы, чтобы не выходить за пределы массива
    valid_indices = zero_indices[zero_indices + 1 < len(x)]
    
    # Получаем элементы, которые идут сразу после нулевых
    after_zero_elements = x[valid_indices + 1]
    
    return np.max(after_zero_elements) if len(after_zero_elements) > 0 else None

x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])
y = np.array([6, 2, 1, 3, 32, 2, 5, 7, 6])
z = np.array([10,10,10,5,5,0,0,0,10,0,2,11,0,13])
print(max_after_zero(x))
print(max_after_zero(y))
print(max_after_zero(z))

5
None
13


**2. (0.2 балла)** Реализуйте функцию, принимающую на вход матрицу и некоторое число и возвращающую ближайший к числу элемент матрицы. Например: для X = np.arange(0,10).reshape((2, 5)) и v = 3.6 ответом будет 4.

In [ ]:
def find_closest_element(matrix, value):
    diff = np.abs(matrix - value)
    
    # Находим индекс элемента с минимальной разницей
    min_index = np.argmin(diff)

    # Возвращаем элемент матрицы, соответствующий найденному индексу
    return matrix.flatten()[min_index]

X = np.arange(0, 10).reshape((2, 5))
v = 3.6
print ('Матрица:', X, 'Число:', v, 'Ближайший к числу элемент матрицы:', find_closest_element(X, v), sep='\n')


Матрица:
[[0 1 2 3 4]
 [5 6 7 8 9]]
Число:
3.6
Ближайший к числу элемент матрицы:
4


**3. (0.2 балла)** Реализуйте функцию scale(X), которая принимает на вход матрицу и масштабирует каждый ее столбец (вычитает выборочное среднее и делит на стандартное отклонение). Убедитесь, что в функции не будет происходить деления на ноль. Протестируйте на случайной матрице (для её генерации можно использовать, например, функцию [numpy.random.randint](http://docs.scipy.org/doc/numpy/reference/generated/numpy.random.randint.html)).

In [16]:
def scale(X):
    # Вычисляем среднее и стандартное отклонение для каждого столбца
    mean = np.mean(X, axis=0)
    std = np.std(X, axis=0)
    
    # Избегаем деления на ноль: если std = 0, заменяем его на 1
    std_revised = np.where(std == 0, 1, std)
    
    # Масштабируем столбцы матрицы
    X_scaled = (X - mean) / std_revised
    
    return X_scaled

X = np.random.randint(0, 100, size=(5, 5))
print("Original Matrix:\n", X)
print("\nScaled Matrix:\n", scale(X))

Original Matrix:
 [[55 16 37 23 68]
 [97 69 85 10 15]
 [96 72 58 69 79]
 [92  2 19 58 35]
 [18 89 66 18 19]]

Scaled Matrix:
 [[-0.53547273 -0.98439378 -0.69763315 -0.5381275   0.95885206]
 [ 0.81933779  0.56837022  1.3952663  -1.09333841 -1.09030758]
 [ 0.78708039  0.65626252  0.21801036  1.42646496  1.38414934]
 [ 0.65805082 -1.39455785 -1.48247045  0.95667111 -0.31703979]
 [-1.72899628  1.15431889  0.56682694 -0.75167016 -0.93565403]]


**4. (0.2 балла)** Реализуйте функцию, которая для заданной матрицы находит:
 - определитель
 - след
 - наименьший и наибольший элементы
 - норму Фробениуса
 - собственные числа
 - обратную матрицу

Для тестирования сгенерируйте матрицу с элементами из нормального распределения $\mathcal{N}$(10,1)

In [18]:
def matrix_operations(matrix):
    determinant = np.linalg.det(matrix)
    trace = np.trace(matrix)

    min_element = np.min(matrix)
    max_element = np.max(matrix)

    frobenius_norm = np.linalg.norm(matrix, 'fro')
    eigenvalues = np.linalg.eigvals(matrix)
    inverse_matrix = np.linalg.inv(matrix)

    return {
        "Определитель": determinant,
        "След": trace,
        "Минимальный элемент": min_element,
        "Максимальный элемент": max_element,
        "Фробениусова норма": frobenius_norm,
        "Собственные значения": eigenvalues,
        "Обратная матрица": inverse_matrix
    }

random_matrix = np.random.normal(10, 1, (3, 3))

print("Original Matrix:\n", random_matrix)

matrix_props = matrix_operations(random_matrix)

for key, value in matrix_props.items():
    print(f"{key}: {value}")

Original Matrix:
 [[11.30714275  8.39251677 10.18463386]
 [10.25988279 10.78182287  8.76304929]
 [ 8.67954339 10.52194157 10.29698467]]
Определитель: 110.82848213702505
След: 32.38595029929293
Минимальный элемент: 8.392516765438772
Максимальный элемент: 11.307142754282427
Фробениусова норма: 29.872899676233953
Собственные значения: [29.73133772+0.j          1.32730629+1.40211395j  1.32730629-1.40211395j]
Обратная матрица: [[ 0.1697756   0.18717667 -0.32721625]
 [-0.26695836  0.2529269   0.04879703]
 [ 0.12968316 -0.41622768  0.32307013]]


**5. (0.2 балла)** Повторите 100 раз следующий эксперимент: сгенерируйте две матрицы размера 10×10 из стандартного нормального распределения, перемножьте их (как матрицы) и найдите максимальный элемент. Какое среднее значение по экспериментам у максимальных элементов? 95-процентная квантиль?

In [6]:
def calculate_max_elements(num_experiments):
    max_elements = []

    for _ in range(num_experiments):
        matrix1 = np.random.randn(10, 10)
        matrix2 = np.random.randn(10, 10)

        result_matrix = np.dot(matrix1, matrix2)
        max_element = np.max(result_matrix)
        max_elements.append(max_element)
    
    mean_max_element = np.mean(max_elements)
    quantile_95 = np.percentile(max_elements, 95)

    return mean_max_element, quantile_95

num_experiments = 100
mean_max, quantile_95 = calculate_max_elements(num_experiments)

print(f"Среднее максимальное значение: {mean_max}")
print(f"95-й перцентиль: {quantile_95}")

Среднее максимальное значение: 8.359534676021545
95-й перцентиль: 12.144158799143964


### Pandas

![](https://metrouk2.files.wordpress.com/2015/10/panda.jpg)

#### Ответьте на вопросы о данных по авиарейсам в США за январь-апрель 2008 года.

[Данные](https://www.kaggle.com/datasets/prajitdatta/data-stories-of-us-airlines).

In [22]:
import pandas as pd

**6. (0.3 балла)** Какая из причин отмены рейса (`CancellationCode`) была самой частой? (расшифровки кодов можно найти в описании данных)

In [23]:
def find_most_common_cancellation_code(data_frame):
    df = pd.read_csv(data_frame, low_memory=False)
    most_common_cancellation_code = df['CancellationCode'].mode().values[0]
    return most_common_cancellation_code

file_path = 'airline_dec_2008_50k.csv'

result = find_most_common_cancellation_code(file_path)

print(f"Наиболее часто встречающийся код отмены: {result}")

Наиболее часто встречающийся код отмены: B


**7. (0.3 балла)** Найдите среднее, минимальное и максимальное расстояние, пройденное самолетом.

In [24]:
def calculate_distance_statistics(data_frame):
    df = pd.read_csv(data_frame, low_memory=False)

    mean_distance = df['Distance'].mean()
    min_distance = df['Distance'].min()
    max_distance = df['Distance'].max()

    return mean_distance, min_distance, max_distance

file_path = 'airline_dec_2008_50k.csv'

mean_dist, min_dist, max_dist = calculate_distance_statistics(file_path)

print(f"Среднее расстояние: {mean_dist}")
print(f"Минимальное расстояние: {min_dist}")
print(f"Максимальное расстояние: {max_dist}")

Среднее расстояние: 572.15812
Минимальное расстояние: 30
Максимальное расстояние: 3303


**8. (0.3 балла)** Не выглядит ли подозрительным минимальное пройденное расстояние? В какие дни и на каких рейсах оно было? Какое расстояние было пройдено этими же рейсами в другие дни?

In [31]:
file_path = 'airline_dec_2008_50k.csv'  # Укажите путь к файлу
df = pd.read_csv(file_path, low_memory=False)

min_distance = df['Distance'].min()

suspicious_flights = df[df['Distance'] == min_distance]

print("Подозрительные рейсы с минимальным расстоянием:")
print(suspicious_flights[['Year', 'Month', 'DayofMonth', 'FlightNum', 'Origin', 'Dest', 'Distance']])

# Проверяем, какое расстояние пройдено этими же рейсами в другие дни
same_flights_other_days = df[(df['FlightNum'].isin(suspicious_flights['FlightNum'])) &
                             (~df.index.isin(suspicious_flights.index))]

print("\nРасстояния этих же рейсов в другие дни:")
print(same_flights_other_days[['Year', 'Month', 'DayofMonth', 'FlightNum', 'Origin', 'Dest', 'Distance']])

suspicious_flights2 = df[df['Distance'] < 100]
print(f"Еще пару подозрительных рейсов\n")
print(suspicious_flights2[['Year', 'Month', 'DayofMonth', 'FlightNum', 'Origin', 'Dest', 'Distance']])

Подозрительные рейсы с минимальным расстоянием:
       Year  Month  DayofMonth  FlightNum Origin Dest  Distance
16788  2008     12          31       5613    SFO  SJC        30

Расстояния этих же рейсов в другие дни:
       Year  Month  DayofMonth  FlightNum Origin Dest  Distance
433    2008     12           1       5613    CVG  MEM       403
15982  2008     12          28       5613    MDT  CVG       429
19656  2008     12           1       5613    MDT  CVG       429
22266  2008     12           2       5613    MDT  CVG       429
24371  2008     12           2       5613    CVG  MEM       403
25164  2008     12           3       5613    MDT  CVG       429
27058  2008     12           3       5613    CVG  MEM       403
28344  2008     12           4       5613    MDT  CVG       429
29541  2008     12           4       5613    CVG  MEM       403
29882  2008     12           5       5613    MDT  CVG       429
32027  2008     12           5       5613    CVG  MEM       403
32300  2008    

**9. (0.3 балла)** Из какого аэропорта было произведено больше всего вылетов? В каком городе он находится?

In [26]:
file_path = 'airline_dec_2008_50k.csv'  # Укажите путь к файлу
df = pd.read_csv(file_path, low_memory=False)

most_departures_airport = df['Origin'].value_counts().idxmax()
most_departures_count = df['Origin'].value_counts().max()

print(f"Больше всего вылетов было произведено из аэропорта: {most_departures_airport}")
print(f"Количество вылетов: {most_departures_count}")

airport_city_mapping = {
    'ATL': 'Atlanta, GA',
    'LAX': 'Los Angeles, CA',
    'ORD': 'Chicago, IL',
}

most_departures_city = airport_city_mapping.get(most_departures_airport, "Unknown City")
print(f"Аэропорт находится в городе: {most_departures_city}")

Больше всего вылетов было произведено из аэропорта: ORD
Количество вылетов: 3056
Аэропорт находится в городе: Chicago, IL


**10. (0.3 балла)** Найдите для каждого аэропорта среднее время полета (`AirTime`) по всем вылетевшим из него рейсам. Какой аэропорт имеет наибольшее значение этого показателя?

In [27]:
file_path = 'airline_dec_2008_50k.csv'
df = pd.read_csv(file_path, low_memory=False)

# Убираем пропущенные значения в столбце 'AirTime'
df = df.dropna(subset=['AirTime'])

# Вычисляем среднее время полета для каждого аэропорта отправления
mean_airtime_by_airport = df.groupby('Origin')['AirTime'].mean()

max_mean_airtime_airport = mean_airtime_by_airport.idxmax()
max_mean_airtime_value = mean_airtime_by_airport.max()

mean_airtime_by_airport, max_mean_airtime_airport, max_mean_airtime_value

print(mean_airtime_by_airport)
print(f"Аэропорт с наибольшим средним временем полета: {max_mean_airtime_airport}")
print(f"Среднее время полета для этого аэропорта: {max_mean_airtime_value:.2f} минут")

Origin
ABE    95.171429
ABI    31.945946
ABQ    78.874439
ABY    34.076923
ACT    26.461538
         ...    
TYS    91.580645
VLD    43.000000
VPS    65.955556
XNA    71.073394
YUM    46.280000
Name: AirTime, Length: 260, dtype: float64
Аэропорт с наибольшим средним временем полета: PSE
Среднее время полета для этого аэропорта: 182.12 минут


**11. (0.5 балла)** Найдите аэропорт, у которого наибольшая доля задержанных (`DepDelay > 0`) рейсов. Исключите при этом из рассмотрения аэропорты, из которых было отправлено меньше 1000 рейсов (используйте функцию `filter` после `groupby`).

In [13]:
file_path = 'airline_dec_2008_50k.csv'  # Укажите путь к файлу
df = pd.read_csv(file_path, low_memory=False)

# Убираем пропущенные значения в столбцах 'DepDelay' и 'Origin'
df = df.dropna(subset=['DepDelay', 'Origin'])

# Определяем функцию для расчета доли задержанных рейсов
def calculate_delay_ratio(group):
    total_flights = len(group)
    delayed_flights = (group['DepDelay'] > 0).sum()
    delay_ratio = delayed_flights / total_flights
    return delay_ratio

# Группируем по аэропортам отправления
grouped = df.groupby('Origin')

# Фильтруем группы по количеству рейсов
filtered_group = grouped.filter(lambda x: len(x) >= 10)

# Вычисляем долю задержанных рейсов
delay_ratios = filtered_group.groupby('Origin').apply(calculate_delay_ratio, include_groups=False)

# Находим аэропорт с наибольшей долей задержанных рейсов
max_delay_airport = delay_ratios.idxmax()
max_delay_ratio = delay_ratios.max()

# Выводим долю задержек для каждого аэропорта
print(delay_ratios)

# Выводим аэропорт с наибольшей долей задержанных рейсов и долю задержек
print(f"Аэропорт с наибольшей долей задержанных рейсов: {max_delay_airport}")
print(f"Доля задержанных рейсов для этого аэропорта: {max_delay_ratio:.2%}")



Origin
ABE    0.230769
ABI    0.108108
ABQ    0.135965
ABY    0.000000
ACT    0.153846
         ...   
TYS    0.212121
VLD    0.230769
VPS    0.127660
XNA    0.223214
YUM    0.160000
Length: 249, dtype: float64
Аэропорт с наибольшей долей задержанных рейсов: JNU
Доля задержанных рейсов для этого аэропорта: 63.33%


## Линейная регрессия

В этой части мы разберемся с линейной регрессией, способами её обучения и измерением качества ее прогнозов. 

Будем рассматривать датасет из предыдущей части задания для предсказания времени задержки отправления рейса в минутах (DepDelay). Отметим, что под задержкой подразумевается не только опоздание рейса относительно планируемого времени вылета, но и отправление до планируемого времени.

### Подготовка данных

**12. (0.5 балла)** Считайте выборку из файла при помощи функции pd.read_csv и ответьте на следующие вопросы:
   - Имеются ли в данных пропущенные значения?
   - Сколько всего пропущенных элементов в таблице "объект-признак"?
   - Сколько объектов имеют хотя бы один пропуск?
   - Сколько признаков имеют хотя бы одно пропущенное значение?

In [14]:
import pandas as pd

df = pd.read_csv('airline_dec_2008_50k.csv', low_memory=False)

any_null_values = df.isnull().any().any()
total_null_elements = df.isnull().sum().sum()
objects_with_nulls = df.isnull().any(axis=1).sum()
features_with_nulls = df.isnull().any().sum()

print(f"Имеются ли в данных пропущенные значения?: {any_null_values}")
print(f"Сколько всего пропущенных элементов в таблице 'объект-признак'?: {total_null_elements}")
print(f"Сколько объектов имеют хотя бы один пропуск?: {objects_with_nulls}")
print(f"Сколько признаков имеют хотя бы одно пропущенное значение?: {features_with_nulls}")

Имеются ли в данных пропущенные значения?: True
Сколько всего пропущенных элементов в таблице 'объект-признак'?: 411549
Сколько объектов имеют хотя бы один пропуск?: 50000
Сколько признаков имеют хотя бы одно пропущенное значение?: 15


Как вы понимаете, также не имеет смысла рассматривать при решении поставленной задачи объекты с пропущенным значением целевой переменной. В связи с этим ответьте на следующие вопросы и выполните соответствующие действия:
- Имеются ли пропущенные значения в целевой переменной?
- Проанализируйте объекты с пропущенными значениями целевой переменной. Чем вызвано это явление? Что их объединяет? Можно ли в связи с этим, на ваш взгляд, исключить какие-то признаки из рассмотрения? Обоснуйте свою точку зрения.

Исключите из выборки объектыф **с пропущенным значением целевой переменной и со значением целевой переменной, равным 0**, а также при необходимости исключите признаки в соответствии с вашим ответом на последний вопрос из списка и выделите целевую переменную в отдельный вектор, исключив её из матрицы "объект-признак".

In [15]:
df = pd.read_csv('airline_dec_2008_50k.csv', low_memory=False)

# Проверка на наличие пропущенных значений в целевой переменной
missing_target_values = df['Cancelled'].isnull()
# missing_target_values = df['Cancelled'].isnull().sum()

# Фильтрация данных: удаление строк с пропущенными значениями и неотмененными рейсами
df = df.dropna(subset=['Cancelled'])
df = df[df['Cancelled'] != 0]

# Удаление ненужного столбца
df = df.drop(columns=['CancellationCode', 'Cancelled'])

# Вывод сообщения о наличии пропущенных значений
print(f"Имеются ли пропущенные значения в целевой переменной?: {missing_target_values}")


Имеются ли пропущенные значения в целевой переменной?: 0        False
1        False
2        False
3        False
4        False
         ...  
49995    False
49996    False
49997    False
49998    False
49999    False
Name: Cancelled, Length: 50000, dtype: bool


**13. (0.5 балла)** Обратите внимание, что признаки DepTime, CRSDepTime, ArrTime, CRSArrTime приведены в формате hhmm, в связи с чем будет не вполне корректно рассматривать их как вещественные.

Преобразуйте каждый признак FeatureName из указанных в пару новых признаков FeatureName\_Hour, FeatureName\_Minute, разделив каждое из значений на часы и минуты. Не забудьте при этом исключить исходный признак из выборки. В случае, если значение признака отсутствует, значения двух новых признаков, его заменяющих, также должны отсутствовать. 

Например, признак DepTime необходимо заменить на пару признаков DepTime_Hour, DepTime_Minute. При этом, например, значение 155 исходного признака будет преобразовано в значения 1 и 55 признаков DepTime_Hour, DepTime_Minute соответственно.

In [16]:
import pandas as pd
import numpy as np

# Загрузка данных из файла
file_path = './airline_dec_2008_50k.csv'
data = pd.read_csv(file_path, low_memory=False)

# Список признаков для преобразования
time_features = ['DepTime', 'CRSDepTime', 'ArrTime', 'CRSArrTime']

for feature in time_features:
    # Функция для извлечения часов и минут
    def extract_hour_minute(value):
        if pd.isnull(value):
            return pd.Series([np.nan, np.nan])
        try:
            # Преобразуем значение в строку, удаляем десятичные точки и заполняем нулями слева до 4 символов
            value_str = f"{int(value):04d}"
            hour = int(value_str[:-2])
            minute = int(value_str[-2:])
            return pd.Series([hour, minute])
        except:
            return pd.Series([np.nan, np.nan])
    
    # Применяем функцию к каждому значению признака
    data[[f"{feature}_Hour", f"{feature}_Minute"]] = data[feature].apply(extract_hour_minute)
    
    # Удаляем исходный признак
    data.drop(columns=feature, inplace=True)

# Для проверки результатов можно вывести первые несколько строк
print(data)


       Unnamed: 0  Year  Month  DayofMonth  DayOfWeek UniqueCarrier  \
0               1  2008     12           1          1            WN   
1               2  2008     12           1          1            US   
2               3  2008     12           1          1            MQ   
3               4  2008     12           1          1            EV   
4               5  2008     12           1          1            NW   
...           ...   ...    ...         ...        ...           ...   
49995       49996  2008     12          13          6            YV   
49996       49997  2008     12          13          6            CO   
49997       49998  2008     12          13          6            WN   
49998       49999  2008     12          13          6            AA   
49999       50000  2008     12          13          6            MQ   

       FlightNum TailNum  ActualElapsedTime  CRSElapsedTime  ...  \
0             16  N366SW                NaN              60  ...   
1          

**14. (0.5 балла)** Некоторые из признаков, отличных от целевой переменной, могут оказывать чересчур значимое влияние на прогноз, поскольку по своему смыслу содержат большую долю информации о значении целевой переменной. Изучите описание датасета и исключите признаки, сильно коррелирующие с ответами. Ваш выбор признаков для исключения из выборки обоснуйте. Кроме того, исключите признаки TailNum и Year.

In [17]:
dtype = {'CancellationCode': str}
df = pd.read_csv('airline_dec_2008_50k.csv', dtype=dtype, low_memory=False)

# Удаляем ненужные столбцы
df = df.drop(['TailNum', 'Year'], axis=1)

# Создаем фиктивные переменные для категориальных данных
dummy_columns = ['UniqueCarrier', 'Origin', 'Dest']
df = pd.get_dummies(df, columns=dummy_columns, dummy_na=True)

# Удаляем столбец 'CancellationCode'
df = df.drop(['CancellationCode'], axis=1)

# Вычисляем корреляцию с целевой переменной 'Cancelled'
correlation_with_target = df.corr()['Cancelled'].sort_values(ascending=False)
print("Корреляция с целевой переменной (Cancelled):")
print(correlation_with_target)

# Порог корреляции
correlation_threshold = 0.5

# Выбираем признаки с корреляцией выше порога
highly_correlated_features = correlation_with_target[abs(correlation_with_target) > correlation_threshold].index.tolist()
print(f"\nПризнаки с корреляцией выше {correlation_threshold}: {highly_correlated_features}")

# Удаляем высоко коррелированные признаки
df = df.drop(highly_correlated_features, axis=1)
print(f"\nПосле удаления высоко коррелированных признаков: {df.columns.tolist()}")


Корреляция с целевой переменной (Cancelled):
Cancelled            1.000000
CRSArrTime           0.695137
DayofMonth           0.660181
CRSDepTime           0.602015
DepTime              0.306075
                       ...   
SecurityDelay             NaN
LateAircraftDelay         NaN
UniqueCarrier_nan         NaN
Origin_nan                NaN
Dest_nan                  NaN
Name: Cancelled, Length: 598, dtype: float64

Признаки с корреляцией выше 0.5: ['Cancelled', 'CRSArrTime', 'DayofMonth', 'CRSDepTime', 'Unnamed: 0']

После удаления высоко коррелированных признаков: ['Month', 'DayOfWeek', 'DepTime', 'ArrTime', 'FlightNum', 'ActualElapsedTime', 'CRSElapsedTime', 'AirTime', 'ArrDelay', 'DepDelay', 'Distance', 'TaxiIn', 'TaxiOut', 'Diverted', 'CarrierDelay', 'WeatherDelay', 'NASDelay', 'SecurityDelay', 'LateAircraftDelay', 'UniqueCarrier_9E', 'UniqueCarrier_AA', 'UniqueCarrier_AS', 'UniqueCarrier_B6', 'UniqueCarrier_CO', 'UniqueCarrier_DL', 'UniqueCarrier_EV', 'UniqueCarrier_F9', 'Unique

**15. (1 балл)** Приведем данные к виду, пригодному для обучения линейных моделей. Для этого вещественные признаки надо отмасштабировать, а категориальные — привести к числовому виду. Также надо устранить пропуски в данных.

Некоторые из признаков в нашем датасете являются категориальными. Типичным подходом к работе с ними является бинарное, или [one-hot-кодирование](https://en.wikipedia.org/wiki/One-hot).

Реализуйте функцию transform_data, которая принимает на вход DataFrame с признаками и выполняет следующие шаги:
1. Замена пропущенных значений на нули для вещественных признаков и на строки 'nan' для категориальных.
2. Масштабирование вещественных признаков с помощью [StandardScaler](http://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.StandardScaler.html).
3. One-hot-кодирование категориальных признаков с помощью [DictVectorizer](http://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.DictVectorizer.html) или функции [pd.get_dummies](http://pandas.pydata.org/pandas-docs/stable/generated/pandas.get_dummies.html).

Метод должен возвращать преобразованный DataFrame, который должна состоять из масштабированных вещественных признаков и закодированных категориальных (исходные признаки должны быть исключены из выборки).

In [18]:
import pandas as pd
from sklearn.preprocessing import StandardScaler

def transform_data(df):
    # Замена пропущенных значений
    for column in df.columns:
        if df[column].dtype == 'object':  # категориальные признаки
            df[column] = df[column].fillna('nan')
        else:  # вещественные признаки
            df[column] = df[column].fillna(0)
    
    # Определение вещественных и категориальных признаков
    numeric_columns = df.select_dtypes(include=['int64', 'float64']).columns
    categorical_columns = df.select_dtypes(include=['object']).columns
    
    # Масштабирование вещественных признаков
    scaler = StandardScaler()
    df[numeric_columns] = scaler.fit_transform(df[numeric_columns])
    
    # One-hot кодирование категориальных признаков
    df_encoded = pd.get_dummies(df, columns=categorical_columns, drop_first=True)
    
    return df_encoded




Примените функцию transform_data к данным. Сколько признаков получилось после преобразования?


In [19]:
df = pd.read_csv('airline_dec_2008_50k.csv', low_memory=False)

transformed_df = transform_data(df)

print(transformed_df.head())

   Unnamed: 0  Year  Month  DayofMonth  DayOfWeek   DepTime  CRSDepTime  \
0   -1.732016   0.0    0.0   -1.319756  -1.426318 -1.070215    0.042399   
1   -1.731947   0.0    0.0   -1.319756  -1.426318 -1.070215    0.042399   
2   -1.731878   0.0    0.0   -1.319756  -1.426318 -1.070215    0.042399   
3   -1.731808   0.0    0.0   -1.319756  -1.426318 -1.070215    0.042399   
4   -1.731739   0.0    0.0   -1.319756  -1.426318 -1.070215    0.042399   

    ArrTime  CRSArrTime  FlightNum  ...  Dest_TYS  Dest_VLD  Dest_VPS  \
0 -1.207053    0.046675  -1.217388  ...     False     False     False   
1 -1.207053    0.066854  -0.222447  ...     False     False     False   
2 -1.207053    0.097123   0.265575  ...     False     False     False   
3 -1.207053    0.302952   1.127762  ...     False     False     False   
4 -1.207053    0.302952  -0.560708  ...     False     False     False   

   Dest_WRG  Dest_XNA  Dest_YAK  Dest_YUM  CancellationCode_B  \
0     False     False     False     False    

**16. (0.5 балла)** Разбейте выборку и вектор целевой переменной на обучение и контроль в отношении 70/30 (для этого можно использовать, например, функцию [train_test_split](http://scikit-learn.org/stable/modules/generated/sklearn.cross_validation.train_test_split.html)). 

In [20]:
import pandas as pd
from sklearn.model_selection import train_test_split

# Загрузка данных
df = pd.read_csv('airline_dec_2008_50k.csv', low_memory=False)

# Преобразование данных
transformed_df = transform_data(df)

# Определение целевой переменной (например, 'Cancelled')
X = transformed_df.drop('Cancelled', axis=1)  # Признаки
y = transformed_df['Cancelled']  # Целевая переменная

# Разбиение на обучающую и контрольную выборки
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Проверка размеров выборок
print(f"Размер обучающей выборки: {X_train.shape}")
print(f"Размер контрольной выборки: {X_test.shape}")


Размер обучающей выборки: (35000, 4841)
Размер контрольной выборки: (15000, 4841)


### Scikit-learn

<img src = "https://pp.vk.me/c4534/u35727827/93547647/x_d31c4463.jpg">
Теперь, когда мы привели данные к пригодному виду, попробуем решить задачу при помощи метода наименьших квадратов. Напомним, что данный метод заключается в оптимизации функционала $MSE$:

$$MSE(X, y) = \frac{1}{l} \sum_{i=1}^l (<w, x_i> - y_i)^2 \to \min_{w},$$

где $\{ (x_i, y_i ) \}_{i=1}^l$ — обучающая выборка, состоящая из $l$ пар объект-ответ.

Заметим, что решение данной задачи уже реализовано в модуле sklearn в виде класса [LinearRegression](http://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LinearRegression.html#sklearn.linear_model.LinearRegression).

**17. (0.5 балла)** Обучите линейную регрессию на 1000 объектах из обучающей выборки и выведите значения $MSE$ и $R^2$ на этой подвыборке и контрольной выборке (итого 4 различных числа). Проинтерпретируйте полученный результат — насколько качественные прогнозы строит полученная модель? Какие проблемы наблюдаются в модели?

**Подсказка**: изучите значения полученных коэффициентов $w$, сохраненных в атрибуте coef_ объекта LinearRegression.

In [21]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

model = LinearRegression()
model.fit(X_train, y_train)

y_train_pred = model.predict(X_train)
y_test_pred = model.predict(X_test)

mse_train = mean_squared_error(y_train, y_train_pred)
r2_train = r2_score(y_train, y_train_pred)
mse_test = mean_squared_error(y_test, y_test_pred)
r2_test = r2_score(y_test, y_test_pred)

print(f'MSE на обучающей выборке: {mse_train}')
print(f'R^2 на обучающей выборке: {r2_train}')
print(f'MSE на контрольной выборке: {mse_test}')
print(f'R^2 на контрольной выборке: {r2_test}')

MSE на обучающей выборке: 1.9316174906458605e-29
R^2 на обучающей выборке: 1.0
MSE на контрольной выборке: 2.0824070787787003e-29
R^2 на контрольной выборке: 1.0


Для решения описанных вами в предыдущем пункте проблем используем L1- или L2-регуляризацию, тем самым получив Lasso и Ridge регрессии соответственно и изменив оптимизационную задачу одним из следующих образов:
$$MSE_{L1}(X, y) = \frac{1}{l} \sum_{i=1}^l (<w, x_i> - y_i)^2 + \alpha ||w||_1 \to \min_{w},$$
$$MSE_{L2}(X, y) = \frac{1}{l} \sum_{i=1}^l (<w, x_i> - y_i)^2 + \alpha ||w||_2^2 \to \min_{w},$$

где $\alpha$ — коэффициент регуляризации. Один из способов его подбора заключается в переборе некоторого количества значений и оценке качества на кросс-валидации для каждого из них, после чего выбирается значение, для которого было получено наилучшее качество.

**18. (0.5 балла)** Обучите линейные регрессии с L1- и L2-регуляризатором, подобрав лучшее значение параметра регуляризации из списка alpha_grid при помощи кросс-валидации c 5 фолдами на тех же 1000 объектах, что и в п.17. Выведите значения $MSE$ и $R^2$ на обучающей и контрольной выборках. Удалось ли решить указанные вами ранее проблемы?

Для выполнения данного задания вам могут понадобиться реализованные в библиотеке объекты [LassoCV](http://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LassoCV.html), [RidgeCV](http://scikit-learn.org/stable/modules/generated/sklearn.linear_model.RidgeCV.html) и [KFold](http://scikit-learn.org/stable/modules/generated/sklearn.cross_validation.KFold.html).


In [22]:
from sklearn.linear_model import LassoCV, RidgeCV, Lasso, Ridge
from sklearn.model_selection import KFold
from sklearn.metrics import mean_squared_error, r2_score

alpha_grid = [0.01, 0.1, 1]  # Уменьшенное число гиперпараметров

kf = KFold(n_splits=3)  # Уменьшенное число разбиений

lasso_cv = LassoCV(alphas=alpha_grid, cv=kf, n_jobs=-1)
ridge_cv = RidgeCV(alphas=alpha_grid, cv=kf)

lasso_cv.fit(X_train, y_train)
ridge_cv.fit(X_train, y_train)

best_alpha_lasso = lasso_cv.alpha_
best_alpha_ridge = ridge_cv.alpha_

lasso_model = Lasso(alpha=best_alpha_lasso)
ridge_model = Ridge(alpha=best_alpha_ridge)

lasso_model.fit(X_train, y_train)
ridge_model.fit(X_train, y_train)

y_train_pred_lasso = lasso_model.predict(X_train)
y_test_pred_lasso = lasso_model.predict(X_test)
y_train_pred_ridge = ridge_model.predict(X_train)
y_test_pred_ridge = ridge_model.predict(X_test)

mse_train_lasso = mean_squared_error(y_train, y_train_pred_lasso)
r2_train_lasso = r2_score(y_train, y_train_pred_lasso)
mse_test_lasso = mean_squared_error(y_test, y_test_pred_lasso)
r2_test_lasso = r2_score(y_test, y_test_pred_lasso)

mse_train_ridge = mean_squared_error(y_train, y_train_pred_ridge)
r2_train_ridge = r2_score(y_train, y_train_pred_ridge)
mse_test_ridge = mean_squared_error(y_test, y_test_pred_ridge)
r2_test_ridge = r2_score(y_test, y_test_pred_ridge)

print(f"Lasso:")
print(f"Optimal alpha: {best_alpha_lasso}")
print(f"MSE on training set: {mse_train_lasso}")
print(f"R^2 on training set: {r2_train_lasso}")
print(f"MSE on test set: {mse_test_lasso}")
print(f"R^2 on test set: {r2_test_lasso}")

print(f"Ridge:")
print(f"Optimal alpha: {best_alpha_ridge}")
print(f"MSE on training set: {mse_train_ridge}")
print(f"R^2 on training set: {r2_train_ridge}")
print(f"MSE on test set: {mse_test_ridge}")
print(f"R^2 on test set: {r2_test_ridge}")


Lasso:
Optimal alpha: 0.01
MSE on training set: 0.001467658090123241
R^2 on training set: 0.9985291822774842
MSE on test set: 0.001496320908906144
R^2 on test set: 0.9985109976337726
Ridge:
Optimal alpha: 0.01
MSE on training set: 6.123424149629436e-11
R^2 on training set: 0.999999999938634
MSE on test set: 9.71521897321439e-11
R^2 on test set: 0.999999999903323


### Градиентный спуск

В предыдущем разделе мы использовали существующие реализации методов обучения линейной регрессии с регуляризацией и без. Тем не менее, подобные реализации, как правило, имеются лишь для ограниченного набора стандартных методов. В частности, при выходе функционала качества за пределы стандартного множества необходимо самостоятельно реализовывать составляющие процесса решения оптимизационной задачи. Именно этому и посвящен данный раздел задания.

Пусть необходимо минимизировать следующий функционал (Mean Square Percentage Error — модифицированный [RMSPE](https://www.kaggle.com/c/rossmann-store-sales/details/evaluation)):
$$MSPE(\{x_i, y_i\}_{i=1}^l, \, w) = \frac{1}{l}\sum_{i=1}^l \left( \frac{y_i - \langle w, x_i \rangle }{y_i} \right)^2,$$

где $\{x_i, y_i\}_{i=1}^l$ — обучающая выборка, $w$ — вектор весов линейной модели. Будем также рассматривать функционал $MSPE$ с L2-регуляризацией:

$$MSPE(\{x_i, y_i\}_{i=1}^l, \, w) = \frac{1}{l}\sum_{i=1}^l \left( \frac{y_i - \langle w, x_i \rangle }{y_i} \right)^2 + ||w||_2^2.$$

**19. (0 баллов)** Добавьте к объектам обеих выборок из п. 16 единичный признак.

In [23]:
import numpy as np

X_train['constant_feature'] = 1

X_test['constant_feature'] = 1

**20. (1 балл)** Реализуйте функции, которые вычисляют:
 * прогнозы линейной модели;
 * функционал $MSPE$ и его градиент;
 * регуляризованный $MSPE$ и его градиент.

In [1]:
import numpy as np

def linear_model_predict(X, weights):
    return np.dot(X, weights)

In [2]:
def mean_squared_prediction_error(y_true, y_pred):
    n_samples = len(y_true)
    return np.mean((y_true - y_pred) ** 2)

def mspe_gradient(y_true, y_pred, X):
    n_samples = len(y_true)
    error = y_true - y_pred
    gradient = -2 * np.dot(error, X) / n_samples
    return gradient


In [3]:
def regularized_mspe(y_true, y_pred, X, weights, alpha):
    n_samples = len(y_true)
    mse = mean_squared_prediction_error(y_true, y_pred)
    regularization_term = alpha * np.sum(weights ** 2)
    return mse + regularization_term

def regularized_mspe_gradient(y_true, y_pred, X, weights, alpha):
    n_samples = len(y_true)
    error = y_true - y_pred
    gradient = -2 * np.dot(error, X) / n_samples + 2 * alpha * weights
    return gradient

In [4]:
def make_pred(X, w):
    return np.dot(X, w)

def get_reg_func(w, X, y, alpha):
    mse = mean_squared_percentage_error(y, make_pred(X, w))
    regularization_term = alpha * np.sum(w**2)
    return mse + regularization_term

def mean_squared_percentage_error(y_true, y_pred):
    return ((y_true - y_pred) ** 2).mean()

In [5]:
def make_pred(X, w):
    return np.dot(X, w)

def get_reg_grad(w, X, y, alpha):
    mse_grad = gradient_mspe(y, make_pred(X, w), X)
    regularization_grad = 2 * alpha * w
    return mse_grad + regularization_grad

def gradient_mspe(y_true, y_pred, X):
    n = len(y_true)
    grad = -2/n * X.T.dot((y_true - y_pred) / y_true)
    return grad

In [6]:
# Задание входных данных
np.random.seed(42)
X = np.random.rand(10, 3)  # 10 образцов, 3 признака
y_true = np.random.rand(10)  # 10 истинных значений
weights = np.random.rand(3)  # Веса модели
alpha = 0.1  # Коэффициент регуляризации

y_pred = linear_model_predict(X, weights)
mspe = mean_squared_prediction_error(y_true, y_pred)
grad = mspe_gradient(y_true, y_pred, X)
reg_mspe = regularized_mspe(y_true, y_pred, X, weights, alpha)
reg_grad = regularized_mspe_gradient(y_true, y_pred, X, weights, alpha)
pred = make_pred(X, weights)
mse_perc_error = mean_squared_percentage_error(y_true, y_pred)
reg_func = get_reg_func(weights, X, y_true, alpha)
reg_grad_func = get_reg_grad(weights, X, y_true, alpha)

# Вывод результатов
print("Предсказания:", y_pred)
print("MSPE:", mspe)
print("Градиент MSPE:", grad)
print("Регуляризованный MSPE:", reg_mspe)
print("Градиент регуляризованного MSPE:", reg_grad)
print("Предсказания (make_pred):", pred)
print("Mean Squared Percentage Error:", mse_perc_error)
print("Регуляризованный функционал:", reg_func)
print("Градиент регуляризованного функционала:", reg_grad_func)


Предсказания: [0.54165218 0.15568047 0.45667031 0.12995866 0.21298795 0.19108169
 0.21796447 0.17428551 0.45132547 0.35770364]
MSPE: 0.1850541820865908
Градиент MSPE: [-0.30115822 -0.06496132 -0.2290999 ]
Регуляризованный MSPE: 0.2111817894321774
Градиент регуляризованного MSPE: [-0.27675057  0.03407406 -0.22222219]
Предсказания (make_pred): [0.54165218 0.15568047 0.45667031 0.12995866 0.21298795 0.19108169
 0.21796447 0.17428551 0.45132547 0.35770364]
Mean Squared Percentage Error: 0.1850541820865908
Регуляризованный функционал: 0.2111817894321774
Градиент регуляризованного функционала: [-0.25720494  0.98909033  0.44347081]
